# Group Admins
管理者専用のアクションをまとめています

## Companies [/api/admins/:id/companies]

### GET
companyのリストを表示します。 <br>
Cacoo: 45

+ Request
  + Headers
    Content-Type: application/json

+ Response 200 (application/json)

  + Body
      [
          {
              "id": "98296425-f344-46ec-bebd-e91f05620bb8",
              "name": "Peach株式会社"
          },
          {
              "id": "98296425-f344-46ec-bebd-e91f05620bb8",
              "name": "Peach株式会社"
          }
      ]

## Channels [/api/admins/:id/channels]

### GET
メッセージのリストを表示します。 <br>
Cacoo: 45

+ Request
  + Headers
    Content-Type: application/json

+ Response 200 (application/json)

  + Body
      [
          {
              "company_id": "98296425-f344-46ec-bebd-e91f05620bb8",
              "name": "Peach株式会社",
              "projects": [
                  {
                      "id": "1",
                      "name": "社会人用留学斡旋会社のwebサイトデザイン"
                      "channels": [
                          {
                              id: 1,
                              status: "面談",
                              mtg_datetime: "2019-09-01 10:00:00",
                              user: {
                                  display_name: "DH2405"
                              }
                          },
                          {
                              id: 2,
                              status: "面談",
                              mtg_datetime: "2019-09-01 10:00:00",
                              user: {
                                  display_name: "DH2405"
                              }
                          }
                      ]
                  },
                  {
                      "id": "2",
                      "name": "社会人用留学斡旋会社のwebサイトデザイン"
                      "channels": [
                          {
                              id: 3,
                              status: "面談",
                              mtg_datetime: "2019-09-01 10:00:00",
                              user: {
                                  display_name: "DH2405"
                              }
                          },
                          {
                              id: 4,
                              status: "面談",
                              mtg_datetime: "2019-09-01 10:00:00",
                              user: {
                                  display_name: "DH2405"
                              }
                          }
                      ]
                  },
              ]

          },
          {
              "company_id": "98296425-f344-46ec-bebd-e91f05620bb8",
              "name": "Peach株式会社",
              "projects": [
                  {
                      "id": "1",
                      "name": "社会人用留学斡旋会社のwebサイトデザイン"
                      "channels": [
                          {
                              id: 1,
                              status: "面談",
                              mtg_datetime: "2019-09-01 10:00:00",
                              user: {
                                  display_name: "DH2405"
                              }
                          },
                          {
                              id: 2,
                              status: "面談",
                              mtg_datetime: "2019-09-01 10:00:00",
                              user: {
                                  display_name: "DH2405"
                              }
                          }
                      ]
                  },
                  {
                      "id": "2",
                      "name": "社会人用留学斡旋会社のwebサイトデザイン"
                      "channels": [
                          {
                              id: 3,
                              status: "面談",
                              mtg_datetime: "2019-09-01 10:00:00",
                              user: {
                                  display_name: "DH2405"
                              }
                          },
                          {
                              id: 4,
                              status: "面談",
                              mtg_datetime: "2019-09-01 10:00:00",
                              user: {
                                  display_name: "DH2405"
                              }
                          }
                      ]
                  },
              ]
          }
      ]
