# Group Company周り
CompanyとCompanyが持つ情報(Project)

## Companies [/v1/company]

### POST
企業を作成する


## Companies [/v1/company/:company_id/name]

### GET
企業名を取得する <br>
Cacoo: 24~29.6<br>
ナビバーの吹き出し用

+ Request
  + Headers
    Content-Type: application/json

+ Response 200 (application/json)

  + Body

      {
            "name": "Peach株式会社"
      }


## Staffs [/v1/staffs/:staff_id]

### PATCH
スタッフ情報を編集する

## Projects [/v1/company/:company_id/projects]

### GET
企業に紐づく公開されている案件情報を全て取得する <br>
Cacoo: 26, 27, 29.5

+ Request
  + Headers
    Content-Type: application/json

+ Response 200 (application/json)

  + Body

    [
        {
            "id": 1,
            "name": "社会人用留学斡旋会社のwebサイトデザイン",
            "position": ["コンサルタント", "プロジェクトリーダー"],
            "skill_category": ["システム開発（Web/スマホ）", "インフラエンジニア"],
            "contract_style": ["正社員", "業務委託"],
            "phase": ["要件定義", "コーディング"],
            "contract_style": ["正社員", "業務委託"],
            "unit": "時給",
            "min_price-": 2000,
            "max_price-": 4000,
            "closest_stations_line": "丸ノ内線",
            "closest_stations_name": "東京駅",
            "start_date": "2019/01/01",
            "end_date": "2019/02/01",
            "holiday": "土日祝",
            "scheduled_hour_count": 180,
            "skill_details": "【必須】\n・PHP 5年以上の開発経験\n・JavaScript、HTML、CSSなどのフロントエンド技術を使った開発経験3年以上\n・設計書、テストケース等のドキュメント作成スキル",
            "work_content": "開発のお仕事です。",
            "industry": "IT・インターネット・ゲーム",
            "min_settlement_hour": 20,
            "max_settlement_hour": 200,
            "min_working_date_count": 2,
            "is_remotable": true,
            "is_dressable": true,
            "is_newbiable": true,
            "exists_travel_cost": false,
            "is_flex": false,
            "min_personnel": 1,
            "max_personnel": 3,
            "min_mtg_count": 1,
            "max_mtg_count": 3,
            "remarks": "特にありません。",
            "is_opened": false
        },
        {
            "id": 1,
            "name": "社会人用留学斡旋会社のwebサイトデザイン",
            "position": ["コンサルタント", "プロジェクトリーダー"],
            "skill_category": ["システム開発（Web/スマホ）", "インフラエンジニア"],
            "contract_style": ["正社員", "業務委託"],
            "phase": ["要件定義", "コーディング"],
            "contract_style": ["正社員", "業務委託"],
            "unit": "時給",
            "min_price-": 2000,
            "max_price-": 4000,
            "closest_stations_line": "丸ノ内線",
            "closest_stations_name": "東京駅",
            "start_date": "2019/01/01",
            "end_date": "2019/02/01",
            "holiday": "土日祝",
            "scheduled_hour_count": 180,
            "skill_details": "【必須】\n・PHP 5年以上の開発経験\n・JavaScript、HTML、CSSなどのフロントエンド技術を使った開発経験3年以上\n・設計書、テストケース等のドキュメント作成スキル",
            "work_content": "開発のお仕事です。",
            "industry": "IT・インターネット・ゲーム",
            "min_settlement_hour": 20,
            "max_settlement_hour": 200,
            "min_working_date_count": 2,
            "is_remotable": true,
            "is_dressable": true,
            "is_newbiable": true,
            "exists_travel_cost": false,
            "is_flex": false,
            "min_personnel": 1,
            "max_personnel": 3,
            "min_mtg_count": 1,
            "max_mtg_count": 3,
            "remarks": "特にありません。",
            "is_opened": false
        }
    ]

### POST
案件を新規作成する


## Projects [/v1/company/:company_id/projects/:project_id]

### GET
案件情報を取得する <br>
Cacoo: 31

+ Request
  + Headers
    Content-Type: application/json

+ Response 200 (application/json)

  + Body

      {
          "id": 1,
          "name": "社会人用留学斡旋会社のwebサイトデザイン",
          "position": ["コンサルタント", "プロジェクトリーダー"],
          "skill_category": ["システム開発（Web/スマホ）", "インフラエンジニア"],
          "contract_style": ["正社員", "業務委託"],
          "unit": "時給",
          "min_price-": 2000,
          "max_price-": 4000,
          "closest_stations_line": "丸ノ内線",
          "closest_stations_name": "東京駅",
          "phase":
          "start_date": "2019/01/01",
          "end_date": "2019/02/01",
          "holiday": "土日祝",
          "scheduled_hour_count": 180,
          "skill_details": "【必須】\n・PHP 5年以上の開発経験\n・JavaScript、HTML、CSSなどのフロントエンド技術を使った開発経験3年以上\n・設計書、テストケース等のドキュメント作成スキル",
          "work_content": "開発のお仕事です。",
          "industry": "IT・インターネット・ゲーム",
          "min_settlement_hour": 20,
          "max_settlement_hour": 200,
          "min_working_date_count": "週4勤務"
          "is_remotable": true,
          "is_dressable": true,
          "is_newbiable": true,
          "exists_travel_cost": false,
          "is_flex": false,
          "contract_style": "正社員",
          "min_personnel": 1,
          "max_personnel": 3,
          "min_mtg_count": 1,
          "max_mtg_count": 3,
          "remarks": "特にありません。",
          "is_opened": false
      }

### PATCH
案件情報を編集する

### DELETE
案件を削除する

## Projects  [/v1/projects/search?utf8=✓&q~]

### GET
projectの検索を行います <br>
Cacoo: 30

+ Request
  + Headers
    Content-Type: application/json

+ Response 200 (application/json)

  + Body

    [
        {
            "id": 1,
            "name": "社会人用留学斡旋会社のwebサイトデザイン",
            "position": ["コンサルタント", "プロジェクトリーダー"],
            "skill_category": ["システム開発（Web/スマホ）", "インフラエンジニア"],
            "contract_style": ["正社員", "業務委託"],
            "unit": "時給",
            "min_price-": 2000,
            "max_price-": 4000,
            "closest_stations_line": "丸ノ内線",
            "closest_stations_name": "東京駅",
        },
        {
            "id": 2,
            "name": "社会人用留学斡旋会社のwebサイトデザイン",
            "position": ["コンサルタント", "プロジェクトリーダー"],
            "skill_category": ["システム開発（Web/スマホ）", "インフラエンジニア"],
            "contract_style": ["正社員", "業務委託"],
            "unit": "時給",
            "min_price-": 2000,
            "max_price-": 4000,
            "closest_stations_line": "丸ノ内線",
            "closest_stations_name": "東京駅",
        }
    ]

## Offers [/v1/projects/:project_id/offers]

### GET
案件について、オファーした人材一覧を取得する

### POST
人材へのオファーを行う
paramsとして、userが必要です

## Offers [/v1/projects/:project_id/offers/:offer_id]

### PATCH
オファー内容を編集(面談日時の入力など)する

### DELETE
オファーを削除する


## Favorables [/v1/companies/:id/favorables]

### GET
お気に入りした人材一覧を取得する

### POST
人材のお気に入り
paramsとして、userが必要です
