# Group CompanyFavorites
企業がUserに対してお気に入りすることに関する処理をまとめています

## CompanyFavorites [/api/companies/:company_id/favorites]

### GET

お気に入りした人材情報を取得する <br>
Cacoo: 24.5

+ Request
  + Headers
    Content-Type: application/json

+ Response 200 (application/json)

  + Body

      [
          {
              "id": "98296425-f344-46ec-bebd-e91f05620bb8",
              "display_name": "DH2800",
              ”professions": ["エンジニア", "デザイナー"],
              "age": 32,
              "skills": ["C", "PowerPoint"],

          },
          {
              "id": "98296425-f344-46ec-bebd-e91f05620bb8",
              "display_name": "DH2800",
              ”professions": ["エンジニア", "デザイナー"],
              "age": 32,
              "skills": ["C", "PowerPoint"],
          }
      ]

## CompanyFavorites [/api/companies/:company_id/favorites/:user_id]

### POST

人材をお気に入りする <br>
Cacoo: 24.5, 32, 33

+ Request (application/json)

+ Response 200 (application/json)

    + Attribute

        + code: 200 (number)
        + message: Success company_favorite create (string)

+ Response 400 (application/json)

    + Attribute

        + code: 400 (number)
        + message: Bad Request (string)

### DELETE

人材のお気に入りを削除する <br>
Cacoo: 24.5, 32, 33

+ Request (application/json)

+ Response 200 (application/json)

    + Attribute

        + code: 200 (number)
        + message: Success company_favorite delete (string)

+ Response 400 (application/json)

    + Attribute

        + code: 400 (number)
        + message: Bad Request (string)
