# Group 各種マスタ
マスタデータをまとめて取得するAPIをまとめています。

## Skills [/api/skills]

### GET
使用可能なツール、言語、フレームワークなどを全てまとめたもの

+ Request
  + Headers
    Content-Type: application/json

+ Response 200 (application/json)

  + Body

    [
        {
            "id": "1",
            "name": "C"
        },
        {
            "id": "2",
            "name": "デザイナー"
        }
    ]

## Professions [/api/professions]

### GET
専門性(エンジニア、デザイナー、営業、事務)

+ Request
  + Headers
    Content-Type: application/json

+ Response 200 (application/json)

  + Body

    [
        {
            "id": "1",
            "name": "エンジニア"
        },
        {
            "id": "2",
            "name": "デザイナー"
        }
    ]

## Holidays [/api/holidays]

### GET
休日(土日祝、平日、曜日を問わない)

+ Request
  + Headers
    Content-Type: application/json

+ Response 200 (application/json)

  + Body

    [
        {
            "id": "1",
            "name": "土日祝"
        },
        {
            "id": "2",
            "name": "平日"
        }
    ]

## Industries [/api/industries]

### GET
業界

+ Request
  + Headers
    Content-Type: application/json

+ Response 200 (application/json)

  + Body

    [
        {
            "id": "1",
            "name": "IT・インターネット・ゲーム"
        },
        {
            "id": "2",
            "name": "メーカー"
        }
    ]

## ContractStyles [/api/contract_styles]

### GET
契約形態

+ Request
  + Headers
    Content-Type: application/json

+ Response 200 (application/json)

  + Body

    [
        {
            "id": "1",
            "name": "正社員"
        },
        {
            "id": "2",
            "name": "契約社員"
        }
    ]

## Positions [/api/positions]

### GET
契約形態

+ Request
  + Headers
    Content-Type: application/json

+ Response 200 (application/json)

  + Body

    [
        {
            "id": "1",
            "name": "コンサルタント"
        },
        {
            "id": "2",
            "name": "プロジェクトマネージャー(PM/PMO)"
        }
    ]

## SkillCategories [/api/skill_categories]

### GET
スキルカテゴリ

+ Request
  + Headers
    Content-Type: application/json

+ Response 200 (application/json)

  + Body

    [
        {
            "id": "1",
            "name": "システム開発(Web/スマホ)"
        },
        {
            "id": "2",
            "name": "システム開発(ゲーム)"
        }
    ]

## Phases [/api/phases]

### GET
担当工程

+ Request
  + Headers
    Content-Type: application/json

+ Response 200 (application/json)

  + Body

    [
        {
            "id": "1",
            "name": "要求分析"
        },
        {
            "id": "2",
            "name": "要件定義"
        }
    ]


## DevelopmentProcesses [/api/development_processes]

### GET
開発工程

+ Request
  + Headers
    Content-Type: application/json

+ Response 200 (application/json)

  + Body

    [
        {
            "id": "1",
            "name": "要件定義"
        },
        {
            "id": "2",
            "name": "基本設計"
        }
    ]

## DesignTypes [/api/design_types]

### GET
デザインの種類

+ Request
  + Headers
    Content-Type: application/json

+ Response 200 (application/json)

  + Body

    [
        {
            "id": "1",
            "name": "グラフィック"
        },
        {
            "id": "2",
            "name": "UI/UX"
        }
    ]
