# Group Staffs
企業の担当者が行う処理をまとめてます。
担当者のアクセス権限が必要です。

## Staffs [/v1/company/:company_id/staffs/:staff_id]

### PATCH
スタッフ情報を編集します


## Projects [/v1/company/:company_id/projects]

### GET
案件情報を取得します

### POST
案件を新規作成します


## Projects [/v1/company/:company_id/projects/:project_id]

### PATCH
案件情報を編集します

### DELETE
案件を削除します


## Offers [/v1/company/:company_id/projects/:project_id/offers]

### POST
人材へのオファーを行います
paramsとして、userが必要です

## Offers [/v1/company/:company_id/projects/:project_id/offers/:offer_id]

### PATCH
オファー内容の編集(面談日時の入力など)を行います

### DELETE
オファーの削除を行います


## users  [/v1/company/:company_id/users?utf8=✓&q~]

### GET
userの検索を行います
