# Group Threads
UserとProjectの担当者とがメッセージをするThreadsについてまとめています

## Threads [/api/users/:user_id/threads]

### GET

Userにひもづくルーム(messageをやり取りする場所)一覧を取得する <br>
Cacoo: 17

+ Request
  + Headers
    Content-Type: application/json

+ Response 200 (application/json)

  + Body

      [
          {
              id: "1",
              status: "未着手",
              mtg_datetime: "2019-07-01 10:00:00",
              project: {
                  id: "1",
                  name: "生保団体保険請求システムのwebフロント開発案件",
              },
              company: {
                  id: "98296425-f344-46ec-bebd-e91f05620bb8"
                  name: "Peach株式会社",
              }

          },
          {
              id: "2",
              status: "未着手",
              mtg_datetime: "2019-07-01 10:00:00",
              project: {
                  id: "1",
                  name: "生保団体保険請求システムのwebフロント開発案件",
              },
              company: {
                  id: "98296425-f344-46ec-bebd-e91f05620bb8"
                  name: "Peach株式会社",
              }
          }
      ]

## Threads [/api/users/:user_id/threads/:project_id]

### POST
Threadを作成する <br>
UserFavorite、Offerがあれば紐付ける <br>
Cacoo: 18, 21, 31

+ Request (application/json)
    + Headers
      Content-Type: application/json

+ Response 200 (application/json)

    + Attribute

        + code: 200 (number)
        + message: Success thread create (string)

+ Response 400 (application/json)

    + Attribute

        + code: 400 (number)
        + message: Bad Request (string)

## Threads [/api/companies/:company_id/threads]

### GET

企業が持つ案件ごとにThreadを取得する <br>
Cacoo: 23

+ Request
  + Headers
    Content-Type: application/json

+ Response 200 (application/json)

  + Body

      [
          {
              id: "1",
              name: "京橋インフラエンジニア案件",
              threads: [
                  {
                      status: "未着手",
                      mtg_datetime: "2019-09-01 10:00:00",
                      user: {
                          display_name: "DH2405"
                      }
                  },
                  {
                      status: "未着手",
                      mtg_datetime: "2019-09-01 10:00:00",
                      user: {
                          display_name: "DH2405"
                      }
                  }
              ]
          },
          {
              id: "2",
              name: "京橋インフラエンジニア案件",
              threads: [
                  {
                      status: "未着手",
                      mtg_datetime: "2019-09-01 10:00:00",
                      user: {
                          display_name: "DH2405"
                      }
                  },
                  {
                      status: "未着手",
                      mtg_datetime: "2019-09-01 10:00:00",
                      user: {
                          display_name: "DH2405"
                      }
                  }
              ]
          }
      ]


## Threads [/api/companies/:company_id/threads/:thread_id]

###PATCH

面談日時を入力する <br>
Cacoo: 23.5

+ Request (application/json)

    + Attribute
        + mtg_datetime: 2019-09-01 10:00:00 (string) - 面談日時


+ Response 200 (application/json)

    + Attribute

        + code: 200 (number)
        + message: Success thread update (string)

+ Response 400 (application/json)

    + Attribute

        + code: 400 (number)
        + message: Bad Request (string)


## Threads [/api/users/:user_id/threads/:thread_id]

### DELETE
Threadを削除する <br>
(企業側からは削除できない) <br>
Cacoo: 17.1

+ Request (application/json)

+ Response 200 (application/json)

    + Attribute

        + code: 200 (number)
        + message: Success thread delete (string)

+ Response 400 (application/json)

    + Attribute

        + code: 400 (number)
        + message: Bad Request (string)
