# Group UserFavorites
ユーザーが案件に対してお気に入りすることに関する処理をまとめています

## UserFavorites [/api/users/:user_id/favorites]

### GET

お気に入りした案件情報を取得する <br>
Cacoo: 18

+ Request
  + Headers
    Content-Type: application/json

+ Response 200 (application/json)

    + Body

        [
            {
                "id": "1",
                "name": "東京駅案件",
                "status": "未着手",
                ”company": {
                    name:  "Peach株式会社",
                }

            },
            {
                "id": "2",
                "name": "東京駅案件",
                "status": "未着手",
                ”company": {
                    name:  "Peach株式会社",
                }
            }
        ]

## UserFavorites [/api/users/:user_id/favorites/:project_id]

### POST

案件をお気に入りする <br>
Cacoo: 18, 21, 30, 31

+ Request (application/json)

+ Response 200 (application/json)

    + Attribute

        + code: 200 (number)
        + message: Success user_favorite create (string)

+ Response 400 (application/json)

    + Attribute

        + code: 400 (number)
        + message: Bad Request (string)

### DELETE

案件のお気に入りを削除する <br>
Cacoo: 18, 21, 30, 31

+ Request (application/json)

+ Response 200 (application/json)

    + Attribute

        + code: 200 (number)
        + message: Success user_favorite delete (string)

+ Response 400 (application/json)

    + Attribute

        + code: 400 (number)
        + message: Bad Request (string)
