# Group User周り
Userと、Userが持つ情報(Portfolios, Skills, Educations, Licenses, Hopes, UserMailAlerts)周りをまとめています。

## Users [/api/users/:id]

### GET

ユーザー情報を取得する <br>
Cacoo: 11, 18, 21.0~21.2, 22, 22.1 <br>
ナビバーの吹き出しにも使用

+ Request
  + Headers
    Content-Type: application/json

+ Response 200 (application/json)

  + Body

    {
        "id": "98296425-f344-46ec-bebd-e91f05620bb8",
        "name": "菊地 航",
        "first_name": "航",
        "last_name": "菊地",
        "first_name_kana": "わたる",
        "last_name_kana": "きくち",
        "display_name": "DH280",
        "sex": "男性",
        "birthdate": "1990-01-01",
        "age": 24,
        "phone_number": "080-1234-5678",
        "email": "foo@example.com",
        "skill_remark": "秘書検定2級",
        "closest_station": "丸ノ内線 四ツ谷駅",
        "closest_station_line": "丸ノ内線",
        "closest_station_name": "四ツ谷駅",
    }

### PATCH
User情報を編集する <br>
Cacoo: 11

+ Request (application/json)

    + Attribute
        + user: (object)
            + first_name: 航 (string) - 名
            + last_name: 菊地 (string) - 姓
            + first_name_kana: わたる (string) - 名ふりがな
            + last_name_kana: きくち (string) - 姓ふりがな
            + sex: male (enum) - 性別
                + male (string) - 男性
                + female (string) - 女性
            + birthdate: 1990/01/01 (string) - 誕生日
            + phone_number: `080-1234-5678` (string) - 電話番号
            + email: foo@example.com (string) - メールアドレス
            + closest_station_line: 丸ノ内線 (string) - 最寄駅の路線
            + closest_station_name: 四ツ谷駅 (string) - 最寄駅の駅名

+ Response 200 (application/json)

    + Attribute

        + code: 200 (number)
        + message: Success user update (string)

+ Response 400 (application/json)

    + Attribute

        + code: 400 (number)
        + message: Bad Request (string)

### DELETE
Userを削除する

## Users  [/api/users/]

### POST
Userを追加する <br>
Cacoo: 1.1

+ Request (application/json)

    + Attribute
        + user: (object)
            + first_name: 航 (string, required) - 名
            + last_name: 菊地 (string, required) - 姓
            + first_name_kana: わたる (string, required) - 名ふりがな
            + last_name_kana: きくち (string, required) - 姓ふりがな
            + sex: male (enum, required) - 性別
                + male (string) - 男性
                + female (string) - 女性
            + birthdate: `1990-01-01` (string, required) - 誕生日
            + phone_number: `080-1234-5678` (string, required) - 電話番号
            + email: foo@example.com (string, required) - メールアドレス
            + user_professions_attributes: (array)
                + (object)
                    + profession_id: 1 (number) - 職種マスタのID
                + (object)
                    + profession_id: 2 (number) - 職種マスタのID

+ Response 200 (application/json)

    + Attribute

        + code: 200 (number)
        + message: Success user create (string)

+ Response 400 (application/json)

    + Attribute

        + code: 400 (number)
        + message: Bad Request (string)

## Users  [/api/users/search]

### POST
userの検索を行います <br>
Cacoo: 32, 45<br>

+ Request
    + Headers
        Content-Type: application/json

    + Attribute
        + q: (object)
            + skills_name_cont: (array)
                + C
                + Ruby
            + user_professions_name_cont: (array)
                + エンジニア
                + デザイナー

+ Response 200 (application/json)

  + Body

    [
        {
            "id": "98296425-f344-46ec-bebd-e91f05620bb8",
            "display_name": "DH280",
            "age": 32,
            "sex": "male",
            "skills": ["Java", "C++"],
            "professions": ["エンジニア"],
        },
        {
            "id": "98296425-f344-46ec-bebd-e91f05620bb5",
            "display_name": "DH281",
            "age": 22,
            "sex": "female",
            "skills": [ "Python", "Javascript" ],
            "professions": ["エンジニア", "デザイナー"]
        },
    ]

## Portfolios [/api/users/:user_id/portfolios/]

### GET
userにひもづく、全てのportfolioを取得する <br>
Cacoo: 13.5

+ Request
  + Headers
    Content-Type: application/json

+ Response 200 (application/json)

  + Body

      [
          {
              "id": 1,
              "image": "http://placehold.jp/150x150.png",
              "title": "社会人用留学斡旋会社のwebサイトデザイン",
              "description": "サイトリニューアルのデザインを担当させていただきました。画像は納品した時のトップページのデザイン案です。",
              "start_date": "2019-01-01",
              "end_date": "2019-03-01",
              "price": "1万円〜2万円",
              "url": "http://example.com/"
          },
          {
              "id": 2,
              "image": "http://placehold.jp/150x150.png",
              "title": "金融系アプリのwebサイトデザイン",
              "description": "サイトリニューアルのデザインを担当させていただきました。画像は納品した時のトップページのデザイン案です。",
              "start_date": "2019-01-01",
              "end_date": "2019-03-01",
              "price": "1万円〜2万円",
              "url": "http://example.com/"
          }
      ]


### POST
portfolioを追加する <br>
Cacoo: 13.5


+ Request (application/json)

    + Attribute
        + portfolio: (object)
            + image: http://placehold.jp/150x150.png (string) - Portfolioのキャプチャ画像など
            + title: 社会人用留学斡旋会社のwebサイトデザイン (string, required) - Portfolioのタイトル
            + description: サイトリニューアルのデザインを担当させていただきました。画像は納品した時のトップページのデザイン案です。 (string) - Portfolioの説明文
            + start_date: `2019-01-01` (string) - Portfolioの開始日
            + end_date: `2019-03-01` (string) - Portfolioの終了日
            + price: _0_5000 (enum, required) - Portfolioの参考価格
                + _0_5000 (string) - 5千円未満
                + _5000_10000 (string) - 5千円〜1万円
                + _10000_20000 (string) - 1万円〜2万円
                + _20000_50000 (string) - 2万円〜5万円
                + _50000_100000 (string) - 5万円〜10万円
                + _100000_200000 (string) - 10万円〜20万円
                + _200000_300000 (string) - 20万円〜30万円
                + _300000_500000 (string) - 30万円〜50万円
                + _500000_1000000 (string) - 50万円〜100万円
                + _1000000_3000000 (string) - 100万円〜300万円
                + _3000000_5000000 (string) - 300万円〜500万円
                + more (string) - 500万円以上
            + url: http://example.com/ (string) - Portfolioの参考URL

+ Response 200 (application/json)

    + Attribute

        + code: 200 (number)
        + message: Success portfolio create (string)

+ Response 400 (application/json)

    + Attribute

        + code: 400 (number)
        + message: Bad Request (string)

## Portfolios [/api/users/:user_id/portfolios/:id]

### PATCH
portfolioを編集する <br>
Cacoo: 13.5

+ Request (application/json)

    + Attribute
        + portfolio: (object)
            + image: http://placehold.jp/150x150.png (string) - Portfolioのキャプチャ画像など
            + title: 社会人用留学斡旋会社のwebサイトデザイン (string) - タイトル
            + description: サイトリニューアルのデザインを担当させていただきました。画像は納品した時のトップページのデザイン案です。 (string) - 説明文
            + start_date: `2019-01-01` (string) - 開始日
            + end_date: `2019-03-01` (string) - 終了日
            + price: _0_5000 (enum) - 参考価格
                + _0_5000 (string) - 5千円未満
                + _5000_10000 (string) - 5千円〜1万円
                + _10000_20000 (string) - 1万円〜2万円
                + _20000_50000 (string) - 2万円〜5万円
                + _50000_100000 (string) - 5万円〜10万円
                + _100000_200000 (string) - 10万円〜20万円
                + _200000_300000 (string) - 20万円〜30万円
                + _300000_500000 (string) - 30万円〜50万円
                + _500000_1000000 (string) - 50万円〜100万円
                + _1000000_3000000 (string) - 100万円〜300万円
                + _3000000_5000000 (string) - 300万円〜500万円
                + more (string) - 500万円以上
            + url: http://example.com/ (string) - 参考URL

+ Response 200 (application/json)

    + Attribute

        + code: 200 (number)
        + message: Success portfolio update (string)

+ Response 400 (application/json)

    + Attribute

        + code: 400 (number)
        + message: Bad Request (string)

### DELETE
portfolioを削除する


## Licenses [/api/users/:user_id/licenses]

### GET
userにひもづく、全てのLicenseの情報を取得する <br>
Cacoo: 12

+ Request
  + Headers
    Content-Type: application/json

+ Response 200 (application/json)

  + Body

      [
          {
              "id": 2,
              "get_date": "2019-01-01",
              "name": "応用情報技術者"
          },
          {
              "id": 3,
              "get_date": "2019-02-01",
              "name": "基本情報技術者"
          }
      ]


### POST
Licenseを追加する
Cacoo: 12

+ Request (application/json)

    + Attribute
        + license: (object)
            + name: 基本情報技術者 (string) - Licenseの名前
            + get_date: `2019-01-01` (string) - Portfolioの開始日

+ Response 200 (application/json)

    + Attribute

        + code: 200 (number)
        + message: Success license create (string)

+ Response 400 (application/json)

    + Attribute

        + code: 400 (number)
        + message: Bad Request (string)

## Licenses [/api/users/:user_id/licenses/:id]

### DELETE
Licenseを削除する


### PATCH
Licenseを編集する <br>
Cacoo: 12

+ Request (application/json)

    + Attribute
        + license: (object)
            + name: 基本情報技術者 (string) - Licenseの名前
            + get_date: `2019-01-01` (string) - Licenseの開始日

+ Response 200 (application/json)

    + Attribute

        + code: 200 (number)
        + message: Success license create (string)

+ Response 400 (application/json)

    + Attribute

        + code: 400 (number)
        + message: Bad Request (string)

## Skills [/api/users/:id/skills]

### GET
userにひもづく、全てのSkillの情報を取得する <br>
Cacoo: 13, 24.0~24.5, 25

+ Request
  + Headers
    Content-Type: application/json

+ Response 200 (application/json)

  + Body
      [
          {
              "skill_id": 35,
              "years_count": 3,
              "name": "Java",
          },
          {
              "skill_id": 36,
              "years_count": 5,
              "name": "C++",
          }
      ]



## Skills [/api/users/:user_id/skills/:id]

### POST
Skillを追加する <br>
Cacoo: 13

+ Request (application/json)

    + Attribute
        + user_skill: (object)
            + years_count: 2 (number, required) - skillの経験年数

+ Response 200 (application/json)

    + Attribute

        + code: 200 (number)
        + message: Success skill create (string)

+ Response 400 (application/json)

    + Attribute

        + code: 400 (number)
        + message: Bad Request (string)

### DELETE
Skillを削除する

## Hopes [/api/users/:user_id/hopes]

### GET
userにひもづく、Hopeの情報を取得する <br>
Cacoo: 14

+ Request
  + Headers
    Content-Type: application/json

+ Response 200 (application/json)

  + Body
      {
          "professions": ["エンジニア", "デザイナー"],
          "min_price": 300000,
          "max_price": 1000000,
          "scheduled_start_date": "2019-10-10",
          "activable_count": 3,
          "residable_count": 2,
          "holiday": "土日祝",
          "appeal_point": "私は天才です",
          "comment": "すごい人です！"
      }


## Hopes [/api/users/:user_id/hopes/:id]

### PATCH
Hopeを編集する <br>
Cacoo: 14

+ Request (application/json)

    + Attribute
        + hope: (object)
            + min_price: 300000 (number) - 最低希望価格
            + max_price: 1000000 (number) - 最高希望価格
            + scheduled_start_date: `2019-10-10` (string) - 稼働開始可能日
            + activable_count: 3 (number) - 1週間のうち働ける日数
            + residable_count: 2 (number) - 1週間のうち常駐できる日数
            + appeal_point: 私は天才です (string) - アピールポイント
            + comment: すごい人です！ (string) - 担当コンサルタントからのコメント
            + holiday_id: 1 (number) - 休日のマスタID

+ Response 200 (application/json)

    + Attribute

        + code: 200 (number)
        + message: Success hope update (string)

+ Response 400 (application/json)

    + Attribute

        + code: 400 (number)
        + message: Bad Request (string)


## Educations [/api/users/:id/educations]

### POST
Educationを追加する <br>
Cacoo: 15

+ Request (application/json)

    + Attribute
        + education: (object)
            + school_name: 早稲田大学 (string, required) - 学校名
            + start_date: `2012-04-01` (string) - 入学日
            + end_date: 2016-03-31 (string) - 卒業日

+ Response 200 (application/json)

    + Attribute

        + code: 200 (number)
        + message: Success education create (string)

+ Response 400 (application/json)

    + Attribute

        + code: 400 (number)
        + message: Bad Request (string)

## Educations [/api/users/:user_id/educations/:id]

### DELETE
Educationを削除する

### PATCH
Educationを編集する <br>
Cacoo: 15

+ Request (application/json)

    + Attribute
        + education: (object)
            + school_name: 早稲田大学 (string) - 学校名
            + start_date: `2012-04-01` (string) - 入学日
            + end_date: `2016-03-31` (string) - 卒業日

+ Response 200 (application/json)

    + Attribute

        + code: 200 (number)
        + message: Success education update (string)

+ Response 400 (application/json)

    + Attribute

        + code: 400 (number)
        + message: Bad Request (string)

## UserMailAlerts [/api/users/:user_id/mail_alert]

### GET
メール通知設定を取得する <br>
Cacoo: 22.5, 22.6

+ Request
  + Headers
    Content-Type: application/json

+ Response 200 (application/json)

  + Body
      {
          "id": 1,
          "needs_when_send_notice": true,
          "needs_when_offered": false,
          "needs_when_favorite_is_changed": false,
          "needs_when_favorite_is_closed": false,
          "needs_before_mtg": false
      }

### PATCH
メール通知設定を編集する <br>
Cacoo: 22.5

+ Request (application/json)

    + Attribute
        + user_mail_alert: (object)
            + needs_when_send_notice: true (boolean, required) - 運営会社からのお知らせ通知メールを受け取る
            + needs_when_offered: false (boolean, required) - 企業から案件をオファーされた時に通知メールを受け取る
            + needs_when_favorite_is_changed: false (boolean, required) - お気に入りした案件の情報が変更された時に通知メールを受け取る
            + needs_when_favorite_is_closed: false (boolean, required) - お気に入りした案件が掲載終了になった時に通知メールを受け取る
            + needs_before_mtg: false (boolean, required) - 確定した面談日の前日に通知メールを受け取る

+ Response 200 (application/json)

    + Attribute

        + code: 200 (number)
        + message: Success user_mail_alert update (string)

+ Response 400 (application/json)

    + Attribute

        + code: 400 (number)
        + message: Bad Request (string)

## Resumes [/api/users/:id/resumes]

### POST
Resumeを追加する <br>
Cacoo: 16.1~4

+ Request (application/json)

    + Attribute
        + resume: (object)
            + company_name: Peach株式会社 (string) - 会社名
            + contract_style_id: 1 (number) - 雇用形態マスタのID
            + start_date: `2018-04-01` (string) - 参画開始日
            + end_date: `2019-03-31` (string) - 参画終了日
            + industry_id: 3　(number) - 業界マスタのID
            + position: コンサルタント (string) - 役職、役割
            + members_count: 5　(number) - チーム人数
            + project_name: 生産管理システムバージョンアップ支援 (string, required) - プロジェクト/業務名
            + project_description: Rails化を行いました。 (string) - プロジェクト/業務概要
            + resume_development_processes_attributes: (array)
                + (object)
                    + development_process_id: 1 (number) - 開発工程マスタのID
                + (object)
                    + development_process_id: 2 (number) - 開発工程マスタのID
            + resume_design_types_attributes: (array)
                + (object)
                    + design_type_id: 1 (number) - デザインの種類マスタのID
                + (object)
                    + design_type_id: 2 (number) - デザインの種類マスタのID

+ Response 200 (application/json)

    + Attribute

        + code: 200 (number)
        + message: Success resume create (string)

+ Response 400 (application/json)

    + Attribute

        + code: 400 (number)
        + message: Bad Request (string)

## Resumes [/api/users/:user_id/resumes/:id]

### DELETE
職務経歴を削除する

### PATCH
職務経歴を編集する <br>
resume_development_processes_attributesなどの複数項目を選択するものは、削除等の対応を行うためこれまでのものを削除し、新規にrelationを貼り直す構造になっています。<br>
resume_development_processes_attributesなどは何もない場合(relationが存在しない場合)はnilで送り、変更がない場合はresume_development_processes_attributes自体を送信しないようにしてください。<br>
Cacoo: 16.1~4

+ Request (application/json)

    + Attribute
        + resume: (object)
            + company_name: Peach株式会社 (string) - 会社名
            + contract_style_id: 3 - 契約形態マスタのID
            + start_date: `2018-04-01` (string) - 参画開始日
            + end_date: `2019-03-31` (string) - 参画終了日
            + industry_id: 4 - 業界マスタのID
            + position: コンサルタント (string) - 役職、役割
            + members_count: 5　(number) - チーム人数
            + project_name: 生産管理システムバージョンアップ支援 (string, required) - プロジェクト/業務名
            + project_description: Rails化を行いました。 (string) - プロジェクト/業務概要
            + resume_development_processes_attributes: (array)
                + (object)
                    + development_process_id: 1 (number) - 開発工程マスタのID
                + (object)
                    + development_process_id: 2 (number) - 開発工程マスタのID
            + resume_design_types_attributes: (array)
                + (object)
                    + design_type_id: 1 (number) - デザインの種類マスタのID
                + (object)
                    + design_type_id: 2 (number) - デザインの種類マスタのID

+ Response 200 (application/json)

    + Attribute

        + code: 200 (number)
        + message: Success resume update (string)

+ Response 400 (application/json)

    + Attribute

        + code: 400 (number)
        + message: Bad Request (string)

## UsersALL [/api/users/:id/all]

### GET

ユーザーに紐づく情報を含めて取得する <br>
Cacoo: 10, 10.5, 33, 33.1


+ Request

  + Headers

    Content-Type: application/json


+ Response 200 (application/json)

  + Body

    {
        "id": "98296425-f344-46ec-bebd-e91f05620bb8",
        "name": "菊地 航",
        "first_name": "航",
        "last_name": "菊地",
        "first_name_kana": "わたる",
        "last_name_kana": "きくち",
        "display_name": "DH280",
        "sex": "male",
        "birthdate": "1990-01-01",
        "age": 24,
        "phone_number": "080-1234-5678",
        "email": "foo@example.com",
        "skill_remark": "秘書検定2級",
        "closest_station": "丸ノ内線 四ツ谷駅",
        "closest_station_line": "丸ノ内線",
        "closest_station_name": "四ツ谷駅",
        "professions": ["エンジニア", "デザイナー", "営業", "事務"],
        "skills": [
            {
                "years_count": 3,
                "name": "Java"
            },
            {
                "years_count": 5,
                "name": "C++"
            }
        ],
        "hope": {
            "id": 1,
            "min_price": 300000,
            "max_price": 1000000,
            "scheduled_start_date": "2019-10-10",
            "activable_count": 3,
            "residable_count": 2,
            "holiday": "土日祝",
            "appeal_point": "私は天才です",
            "comment": "すごい人です！",
        },
        "licenses": [
            {
                "id": 1,
                "get_date": "2019-01-01",
                "name": "応用情報技術者"
            },
            {
                "id": 2,
                "get_date": "2019-02-01",
                "name": "基本情報技術者"
            }
        ],
        "portfolios": [
            {
                "id": 1,
                "image": "http://placehold.jp/150x150.png",
                "title": "社会人用留学斡旋会社のwebサイトデザイン",
                "description": "サイトリニューアルのデザインを担当させていただきました。画像は納品した時のトップページのデザイン案です。",
                "start_date": "2019-01-01",
                "end_date": "2019-03-01",
                "price": "30万円〜50万円",
                "url": "http://example.com/"
            },
            {
                "id": 2,
                "image": "http://placehold.jp/150x150.png",
                "title": "金融系アプリのwebサイトデザイン",
                "description": "サイトリニューアルのデザインを担当させていただきました。画像は納品した時のトップページのデザイン案です。",
                "start_date": "2019-01-01",
                "end_date": "2019-03-01",
                "price": "1万円〜2万円",
                "url": "http://example.com/"
            }
        ],
        "educations": [
            {
                "school_name": "早稲田大学",
                "start_date": "2012-04-01",
                "end_date": "2016-03-31"
            },
            {
                "school_name": "早稲田大学",
                "start_date": "2012-04-01",
                "end_date": "2016-03-31"
            }
        ],
        "resumes": [
            {
                "company_name": "Peach株式会社",
                "contract_style": "正社員",
                "start_date": "2018-04-01",
                "end_date": "2019-03-31",
                "industry": "IT・インターネット・ゲーム",
                "position": "コンサルタント",
                "members_count": "5",
                "project_name": "生産管理システムバージョンアップ支援",
                "project_description": "Rails化を行いました。",
                "resume_development_processes": [
                    {
                        "id": "1",
                        "name": "要件定義"
                    },
                    {
                        "id": "2",
                        "name": "基本設計"
                    }
                ],
                "resume_design_types": [
                    {
                        "id": "1",
                        "name": "グラフィック"
                    },
                    {
                        "id": "2",
                        "name": "UI/UX"
                    }
                ]
            }
        ]

    }

## Notifications [/api/users/:user_id/notifications/]

### GET
お知らせ一覧を取得する

+ Request
  + Headers
    Content-Type: application/json

+ Response 200 (application/json)

  + Body

    [
        {
            "user_notifications_id": "1",
            "is_opened": "false",
            "notification" {
                "id": "2",
                "title": "お気にいりした案件の情報が更新されました。",
                "content": "あなたがお気にいりした<案件名>の情報が更新されました。 \n <案件名>の詳細はこちらからご確認ください。",
                "sent_datetime": "2019-10-10 10:00:00"
            }
        },
        {
            "user_notifications_id": "2",
            "is_opened": "false",
            "notification" {
                "id": "3",
                "title": "お気にいりした案件の情報が更新されました。",
                "content": "あなたがお気にいりした<案件名>の情報が更新されました。 \n <案件名>の詳細はこちらからご確認ください。",
                "sent_datetime": "2019-10-10 10:00:00"
            }
        }
    ]

## Notifications [/api/users/:user_id/notifications/:user_notification_id]

### PATCH
お知らせ詳細を取得する <br>
user_notificationsのis_openedをtrueにする <br>

+ Request
  + Headers
    Content-Type: application/json

+ Response 200 (application/json)

  + Body
        {
            "user_notifications_id": "2",
            "is_opened": "true",
            "notification" {
                "id": "3",
                "title": "お気にいりした案件の情報が更新されました。",
                "content": "あなたがお気にいりした<案件名>の情報が更新されました。 \n <案件名>の詳細はこちらからご確認ください。",
                "sent_datetime": "2019-10-10 10:00:00"
            }
        }
