# Group User周り
Userと、Userが持つ情報(Portfolios, Skills, Educations, Licenses, WorkingConditions, UserMailAlerts)周りをまとめています。

## UsersAll [/v1/users/:id/all]

### GET

ユーザーに紐づく情報を含めて取得する <br>
Cacoo: 10, 10.5, 33, 33.1


+ Request

  + Headers

    Content-Type: application/json


+ Response 200 (application/json)

  + Body

    {
        "id": 1,
        "display_name": "DH280",
        "sex": "男性",
        "birthdate": "2019/01/01",
        "phone_number": "080-1234-5678",
        "email": "foo@example.com",
        "skills": [
            {
                "years_count": 3,
                "name": "Java"
            },
            {
                "years_count": 5,
                "name": "C++"
            }
        ],
        "working_condition" {
            "id": 1,
            "user_id": 1,
            "job_categories": ["エンジニア", "デザイナー", "営業", "事務"],
            "min_price": 300000,
            "max_price": 1000000,
            "scheduled_start_date": "2019/10/10",
            "activable_count": 3,
            "residable_count": 2,
            "desired_holiday": "土日祝",
            "appeal_point": "私は天才です",
            "comment": "すごい人です！",
            "closest_station": "丸ノ内線 四ツ谷駅"
        },
        "lisenses": [
            {
                "id": 1,
                "user_id": 1,
                "get_date": "2019/01/01",
                "name": "応用情報技術者"
            },
            {
                "id": 2,
                "user_id": 1,
                "get_date": "2019/02/01",
                "name": "基本情報技術者"
            }
        ],
        "portfolios": [
            {
                "id": 1,
                "user_id": 1,
                "image": "http://placehold.jp/150x150.png",
                "title": "社会人用留学斡旋会社のwebサイトデザイン",
                "description": "サイトリニューアルのデザインを担当させていただきました。画像は納品した時のトップページのデザイン案です。",
                "creation_start_date": "2019/01/01",
                "creation_end_date": "2019/03/01",
                "price": "500,000",
                "url": "http://example.com/"
            },
            {
                "id": 2,
                "user_id": 1,
                "image": "http://placehold.jp/150x150.png",
                "title": "金融系アプリのwebサイトデザイン",
                "description": "サイトリニューアルのデザインを担当させていただきました。画像は納品した時のトップページのデザイン案です。",
                "creation_start_date": "2019/01/01",
                "creation_end_date": "2019/03/01",
                "price": "500,000",
                "url": "http://example.com/"
            }
        ]

    }


## UsersName [/v1/users/:id/name]

### GET
ユーザーの本名を取得する <br>
ナビバーの吹き出し用

+ Request
  + Headers
    Content-Type: application/json

+ Response 200 (application/json)

  + Body

    {
        "name": "菊地 航"
    }

## Users [/v1/users/:id]

### GET
ユーザー情報を取得する <br>
Cacoo: 11, 18, 21.0~21.2, 22, 22.1

+ Request
  + Headers
    Content-Type: application/json

+ Response 200 (application/json)

  + Body

    {
        "id": 1,
        "first_name": "航",
        "last_name": "菊地",
        "first_name_kana": "わたる",
        "last_name": "きくち",
        "display_name": "DH280",
        "sex": "男性",
        "birthdate": "2019/01/01",
        "phone_number": "080-1234-5678",
        "email": "foo@example.com"
    }

### PATCH
User情報を編集する

## users  [/v1/users/]

### POST
Userを追加する

### DELETE
Userを削除する

## users  [/v1/users/search?utf8=✓&q~]

### GET
userの検索を行います <br>
Cacoo: 32

+ Request
  + Headers
    Content-Type: application/json

+ Response 200 (application/json)

  + Body

    [
        {
            "id": 1,
            "display_name": "DH280",
            "age": 32,
            "sex": "男性",
            "skills": [ "Java", "C++" ], <!--加工が必要! -->
            "job_categories": ["エンジニア"],
        },
        {
            "id": 2,
            "display_name": "DH281",
            "age": 22,
            "sex": "女性",
            "skills": [ "Python", "Javascript" ], <!--加工が必要! -->
            "job_categories": ["エンジニア", "デザイナー"]
        },
    ]




## Portfolios [/v1/users/:id/portfolios/]

### GET
userにひもづく、全てのportfolioを取得する <br>
Cacoo: 13.5

+ Request
  + Headers
    Content-Type: application/json

+ Response 200 (application/json)

  + Body

      [
          {
              "id": 1,
              "user_id": 1,
              "image": "http://placehold.jp/150x150.png",
              "title": "社会人用留学斡旋会社のwebサイトデザイン",
              "description": "サイトリニューアルのデザインを担当させていただきました。画像は納品した時のトップページのデザイン案です。",
              "creation_start_date": "2019/01/01",
              "creation_end_date": "2019/03/01",
              "price": "500,000",
              "url": "http://example.com/"
          },
          {
              "id": 2,
              "user_id": 1,
              "image": "http://placehold.jp/150x150.png",
              "title": "金融系アプリのwebサイトデザイン",
              "description": "サイトリニューアルのデザインを担当させていただきました。画像は納品した時のトップページのデザイン案です。",
              "creation_start_date": "2019/01/01",
              "creation_end_date": "2019/03/01",
              "price": "500,000",
              "url": "http://example.com/"
          }
      ]


### POST
portfolioを追加する

## Portfolios [/v1/portfolios/:portfolio_id]

<!-- 必要なしと判断。全体の情報からフロントで修正してもらう。
### GET
特定のportfolioの情報を取得する <br>
Cacoo:
-->

### PATCH
portfolioを編集する

### DELETE
portfolioを削除する


## Licenses [/v1/users/:id/licenses]

### GET
userにひもづく、全てのLicenseの情報を取得する <br>
Cacoo: 12

+ Request
  + Headers
    Content-Type: application/json

+ Response 200 (application/json)

  + Body

      [
          {
              "id": 1,
              "user_id": 1,
              "get_date": "2019/01/01",
              "name": "応用情報技術者"
          },
          {
              "id": 2,
              "user_id": 1,
              "get_date": "2019/02/01",
              "name": "基本情報技術者"
          }
      ]



### POST
Licenseを追加する


## Licenses [/v1/licenses/:license_id]

### DELETE
資格を削除する


## Skills [/v1/users/:id/skills]

### GET
userにひもづく、全てのSkillの情報を取得する <br>
Cacoo: 13, 24.0~24.5, 25

+ Request
  + Headers
    Content-Type: application/json

+ Response 200 (application/json)

  + Body
      {
          "remark": "秘書検定1級、漢検1級",
          "skill_tools": [
              {
                  "id": 1,
                  "user_id": 1,
                  "years_count": 3,
                  "tool_master": {
                    "id": 1,
                    "name": "Java"
                  }
              },
              {
                  "id": 2,
                  "user_id": 1,
                  "years_count": 5,
                  "tool_master": {
                    "id": 2,
                    "name": "C++"
                  }
              }
          ]
      }

### POST
スキルを追加する


## Skills [/v1/skills/:skill_id]

### DELETE
スキルを削除する

### PATCH
スキルを編集する


## WorkingConditions [/v1/users/:id/working_condition]

### GET
userにひもづく、WorkingConditionの情報を取得する <br>
Cacoo: 14

+ Request
  + Headers
    Content-Type: application/json

+ Response 200 (application/json)

  + Body
      {
          "id": 1,
          "user_id": 1,
          "job_categories": ["エンジニア", "デザイナー", "営業", "事務"],
          "min_price": 300000,
          "max_price": 1000000,
          "scheduled_start_date": "2019/10/10",
          "activable_count": 3,
          "residable_count": 2,
          "desired_holiday": "土日祝",
          "appeal_point": "私は天才です",
          "comment": "すごい人です！",
          "closest_station": "丸ノ内線 四ツ谷駅"
      }

<!-- 不要。users#createと同じタイミングで作成する。
### POST
希望条件を追加する
-->

## WorkingConditions [/v1/users/:id/working_conditions/:working_condition_id]

### DELETE
希望条件を削除する

### PATCH
希望条件を編集する


## Educations [/v1/users/:id/educations]

### POST
学歴を追加する


## UsersMailAlerts [/v1/users/:id/mail_alert]

### PATCH
メール通知設定を編集する

### GET
メール通知設定を取得する <br>
Cacoo: 22.5, 22.6

+ Request
  + Headers
    Content-Type: application/json

+ Response 200 (application/json)

  + Body
      {
          "id": 1,
          "user_id": 1,
          "needs_when_notice_is_send": true,
          "needs_when_offered": false,
          "needs_when_favorite_project_is_changed": false,
          "needs_when_favorite_project_is_closed": false,
          "needs_before_mtg": false
      }



## Educations [/v1/users/:id/educations/:education_id]

### DELETE
学歴を削除する

### PATCH
学歴を編集する


## Resumes [/v1/users/:id/resumes]

### POST
職務経歴を追加する


## Resumes [/v1/users/:id/resumes/:resume_id]

### DELETE
職務経歴を削除する

### PATCH
職務経歴を編集する


## Favorables [/v1/users/:id/favorables]

### GET
お気に入りした案件一覧を取得する

### POST
案件のお気に入り
paramsとして、projectが必要です
