FORMAT: 1A
HOST: https://www.example.com

# MPB Phase2 API

<!-- include(partials/users.apib) -->

<!-- include(partials/user_favorites.apib) -->

<!-- include(partials/companies.apib) -->

<!-- include(partials/company_favorites.apib) -->

<!-- include(partials/offers.apib) -->

<!-- include(partials/channels.apib) -->

<!-- include(partials/masters.apib) -->
